import { useEffect, useMemo, useState } from 'react'
import Decimal from 'decimal.js'
import { AreaChart, Area, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ArrowDownLeft, ArrowUpRight, BarChart3, Download, Home, Landmark, LogOut, Menu, Plus, Search, Settings, Shield, Target, TrendingUp, Upload, WalletCards, X } from 'lucide-react'
import type { User } from 'firebase/auth'
import { categories, seedAssets, seedGoals, seedTransactions } from './data'
import { load, save } from './storage'
import type { EntryKind, Pillar, Transaction } from './types'

type View = 'home'|'common'|'reserve'|'investments'|'settings'
const money = new Intl.NumberFormat('pt-BR', { style:'currency', currency:'BRL' })
const colors = ['#1bc98e','#7c6cf2','#f0ad4e','#f45b69','#46a8e5','#cf72dc','#94a3b8']
const nav = [{id:'home',label:'Início',icon:Home},{id:'common',label:'Uso comum',icon:WalletCards},{id:'reserve',label:'Reserva',icon:Shield},{id:'investments',label:'Investimentos',icon:TrendingUp},{id:'settings',label:'Configurações',icon:Settings}] as const

export default function App({ currentUser, onLogout }: { currentUser?: User; onLogout?: () => Promise<void> }) {
  const [view,setView] = useState<View>('home')
  const [transactions,setTransactions] = useState(() => load('cf-transactions',seedTransactions))
  const [modal,setModal] = useState<EntryKind|null>(null)
  const [search,setSearch] = useState('')
  useEffect(() => save('cf-transactions',transactions),[transactions])
  const income = useMemo(() => transactions.filter(t=>t.kind==='income').reduce((s,t)=>s+t.value,0),[transactions])
  const expense = useMemo(() => transactions.filter(t=>t.kind==='expense').reduce((s,t)=>s+t.value,0),[transactions])
  const balances = { common: income*.5-expense, reserve: income*.3+seedGoals.reduce((s,g)=>s+g.value,0), investments: income*.2+seedAssets.reduce((s,a)=>s+a.currentPrice*a.quantity,0) }
  const total = balances.common+balances.reserve+balances.investments
  const addTransaction = (entry: Omit<Transaction,'id'>) => setTransactions(p=>[{...entry,id:crypto.randomUUID()},...p])
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span>MC</span><div>Meu Controle<small>Finanças 50/30/20</small></div></div><nav>{nav.map(n=><button className={view===n.id?'active':''} onClick={()=>setView(n.id)} key={n.id}><n.icon size={19}/>{n.label}</button>)}</nav><div className="sync"><span></span>Dados salvos neste dispositivo</div></aside>
    <main><header><div><button className="mobile-menu"><Menu/></button><p>VISÃO FINANCEIRA</p><h1>{nav.find(n=>n.id===view)?.label}</h1></div><div className="user-menu"><div><b>{currentUser?.displayName || 'Proprietário'}</b><small>{currentUser?.email}</small></div>{currentUser?.photoURL ? <img className="avatar" src={currentUser.photoURL} referrerPolicy="no-referrer"/> : <div className="avatar">DO</div>}<button onClick={onLogout} title="Sair"><LogOut/></button></div></header>
      {view==='home'&&<HomeView total={total} balances={balances} income={income} expense={expense} transactions={transactions} setModal={setModal}/>} 
      {view==='common'&&<CommonView transactions={transactions} search={search} setSearch={setSearch} income={income}/>} 
      {view==='reserve'&&<ReserveView/>}
      {view==='investments'&&<InvestmentsView freeCash={income*.2}/>} 
      {view==='settings'&&<SettingsView transactions={transactions} setTransactions={setTransactions}/>} 
    </main>
    <div className="fab"><button className="expense" onClick={()=>setModal('expense')} aria-label="Nova saída"><ArrowUpRight/></button><button className="income" onClick={()=>setModal('income')} aria-label="Nova entrada"><Plus/></button></div>
    <nav className="bottom-nav">{nav.slice(0,4).map(n=><button className={view===n.id?'active':''} onClick={()=>setView(n.id)} key={n.id}><n.icon/><span>{n.label.split(' ')[0]}</span></button>)}</nav>
    {modal&&<TransactionModal kind={modal} close={()=>setModal(null)} submit={addTransaction}/>} 
  </div>
}

function HomeView({total,balances,income,expense,transactions,setModal}:{total:number;balances:Record<Pillar,number>;income:number;expense:number;transactions:Transaction[];setModal:(v:EntryKind)=>void}) {
  return <section className="page"><article className="hero"><div><span>PATRIMÔNIO TOTAL</span><strong>{money.format(total)}</strong><small><TrendingUp size={14}/> visão consolidada dos três pilares</small></div><div className="hero-ring"><span>50<small>/30/20</small></span></div></article>
    <div className="pillar-grid"><PillarCard title="Uso comum" percent="50%" value={balances.common} icon={<WalletCards/>} color="green" subtitle={`${money.format(expense)} gastos no mês`} progress={income?expense/(income*.5)*100:0}/><PillarCard title="Reserva" percent="30%" value={balances.reserve} icon={<Shield/>} color="purple" subtitle="Reserva + objetivos" progress={42}/><PillarCard title="Investimentos" percent="20%" value={balances.investments} icon={<TrendingUp/>} color="amber" subtitle="Carteira + caixa livre" progress={68}/></div>
    <div className="content-grid"><article className="panel"><div className="panel-head"><div><span>MOVIMENTAÇÕES</span><h2>Últimos lançamentos</h2></div><BarChart3/></div><TransactionList transactions={transactions.slice(0,5)}/></article><article className="panel quick"><div className="panel-head"><div><span>ATALHOS</span><h2>Lançamento rápido</h2></div></div><button onClick={()=>setModal('income')}><ArrowDownLeft/><div><strong>Registrar entrada</strong><small>Distribuição automática 50/30/20</small></div></button><button onClick={()=>setModal('expense')}><ArrowUpRight/><div><strong>Registrar saída</strong><small>Gasto, resgate ou retirada</small></div></button></article></div>
  </section>
}
function PillarCard({title,percent,value,icon,color,subtitle,progress}:{title:string;percent:string;value:number;icon:React.ReactNode;color:string;subtitle:string;progress:number}) { return <article className={`pillar ${color}`}><div className="pillar-top"><span className="pillar-icon">{icon}</span><b>{percent}</b></div><small>{title.toUpperCase()}</small><strong>{money.format(value)}</strong><div className="progress"><i style={{width:`${Math.min(progress,100)}%`}}/></div><p>{subtitle}</p></article> }

function CommonView({transactions,search,setSearch,income}:{transactions:Transaction[];search:string;setSearch:(s:string)=>void;income:number}) {
 const expenses=transactions.filter(t=>t.kind==='expense'), total=expenses.reduce((s,t)=>s+t.value,0), daily=Math.max(0,(income*.5-total)/Math.max(1,31-new Date().getDate()))
 const pie=categories.map(([name])=>({name,value:expenses.filter(t=>t.category===name).reduce((s,t)=>s+t.value,0)})).filter(x=>x.value)
 const filtered=expenses.filter(t=>(t.description+t.category).toLowerCase().includes(search.toLowerCase()))
 return <section className="page"><div className="metric-row"><Metric label="ORÇAMENTO DO MÊS" value={money.format(income*.5)}/><Metric label="GASTO ATÉ AGORA" value={money.format(total)}/><Metric label="LIMITE DIÁRIO SUGERIDO" value={money.format(daily)}/></div><div className="content-grid"><article className="panel chart"><span>DISTRIBUIÇÃO</span><h2>Gastos por categoria</h2><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={pie} innerRadius={68} outerRadius={98} dataKey="value">{pie.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={v=>money.format(Number(v))}/></PieChart></ResponsiveContainer><div className="legend">{pie.map((p,i)=><span key={p.name}><i style={{background:colors[i]}}/>{p.name}</span>)}</div></article><article className="panel"><span>EXTRATO</span><h2>Saídas do pilar</h2><label className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar lançamento ou categoria"/></label><TransactionList transactions={filtered}/></article></div></section>
}
function ReserveView(){ const total=seedGoals.reduce((s,g)=>s+g.value,0); const projection=Array.from({length:13},(_,i)=>({month:i,value:new Decimal(total).plus(new Decimal(500).times(i)).times(new Decimal(1.009).pow(i)).toNumber()})); return <section className="page"><div className="metric-row"><Metric label="TOTAL EM RESERVA" value={money.format(total)}/><Metric label="META DE EMERGÊNCIA" value={money.format(18000)}/><Metric label="PROGRESSO" value={`${Math.round(total/18000*100)}%`}/></div><div className="goal-grid">{seedGoals.map(g=><article className="goal" key={g.id}><div><Target/><b>{g.name}</b><span>{g.cdi}% do CDI</span></div><strong>{money.format(g.value)} <small>de {money.format(g.target)}</small></strong><div className="progress"><i style={{width:`${g.value/g.target*100}%`}}/></div></article>)}</div><article className="panel chart-wide"><span>SIMULAÇÃO</span><h2>Projeção da reserva — 12 meses</h2><ResponsiveContainer width="100%" height={280}><AreaChart data={projection}><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7c6cf2" stopOpacity=".45"/><stop offset="1" stopColor="#7c6cf2" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#ffffff12" vertical={false}/><XAxis dataKey="month"/><YAxis hide/><Tooltip formatter={v=>money.format(Number(v))}/><Area dataKey="value" stroke="#988cff" fill="url(#area)" strokeWidth={3}/></AreaChart></ResponsiveContainer></article></section> }
function InvestmentsView({freeCash}:{freeCash:number}) { const invested=seedAssets.reduce((s,a)=>s+a.averagePrice*a.quantity,0), current=seedAssets.reduce((s,a)=>s+a.currentPrice*a.quantity,0); return <section className="page"><div className="metric-row"><Metric label="TOTAL INVESTIDO" value={money.format(invested)}/><Metric label="VALOR ATUAL" value={money.format(current)}/><Metric label="CAIXA LIVRE PARA APORTAR" value={money.format(freeCash)}/></div><article className="panel table-panel"><div className="panel-head"><div><span>POSIÇÕES</span><h2>Carteira de ativos</h2></div><button className="primary"><Plus/> Novo ativo</button></div><div className="table-wrap"><table><thead><tr><th>Ativo</th><th>Tipo</th><th>Qtd.</th><th>Preço médio</th><th>Investido</th><th>Valor atual</th><th>Resultado</th></tr></thead><tbody>{seedAssets.map(a=>{const result=(a.currentPrice-a.averagePrice)*a.quantity;return <tr key={a.id}><td><b>{a.ticker}</b></td><td>{a.type}</td><td>{a.quantity}</td><td>{money.format(a.averagePrice)}</td><td>{money.format(a.averagePrice*a.quantity)}</td><td>{money.format(a.currentPrice*a.quantity)}</td><td className={result>=0?'positive':'negative'}>{result>=0?'+':''}{money.format(result)}</td></tr>})}</tbody></table></div></article></section> }
function SettingsView({transactions,setTransactions}:{transactions:Transaction[];setTransactions:(v:Transaction[])=>void}) { const exportData=()=>{const blob=new Blob([JSON.stringify(transactions,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='controle-financeiro.json';a.click();URL.revokeObjectURL(a.href)}; const importData=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(String(reader.result));if(Array.isArray(data))setTransactions(data)}catch{alert('Arquivo JSON inválido')}};reader.readAsText(file)}; return <section className="page"><div className="settings-grid"><article className="panel"><div className="setting-icon"><Upload/></div><h2>Importar dados</h2><p>Restaure um backup JSON exportado pelo sistema.</p><label className="primary file">Selecionar JSON<input type="file" accept="application/json" onChange={e=>importData(e.target.files?.[0])}/></label></article><article className="panel"><div className="setting-icon"><Download/></div><h2>Exportar backup</h2><p>Baixe todos os lançamentos em um arquivo portátil.</p><button className="primary" onClick={exportData}>Baixar JSON</button></article><article className="panel"><div className="setting-icon"><Landmark/></div><h2>Firebase</h2><p>Configure as credenciais em <code>.env.local</code> para ativar login e sincronização em nuvem.</p><span className="status">Configuração pendente</span></article></div></section> }
function Metric({label,value}:{label:string;value:string}) { return <article className="metric"><span>{label}</span><strong>{value}</strong></article> }
function TransactionList({transactions}:{transactions:Transaction[]}) { return <div className="transactions">{transactions.length===0&&<p className="empty">Nenhum lançamento encontrado.</p>}{transactions.map(t=><div className="transaction" key={t.id}><span className={t.kind}><span>{t.kind==='income'?'↙':'↗'}</span></span><div><b>{t.description}</b><small>{t.category} · {new Date(`${t.date}T12:00:00`).toLocaleDateString('pt-BR')}</small></div><strong className={t.kind==='income'?'positive':''}>{t.kind==='income'?'+':'−'} {money.format(t.value)}</strong></div>)}</div> }
function TransactionModal({kind,close,submit}:{kind:EntryKind;close:()=>void;submit:(v:Omit<Transaction,'id'>)=>void}) { const [value,setValue]=useState(''),[description,setDescription]=useState(''),[category,setCategory]=useState('Mercado'),[pillar,setPillar]=useState<Pillar>('common');const numeric=Number(value.replace(/\./g,'').replace(',','.'))||0; const confirm=()=>{if(numeric<=0)return;submit({kind,value:numeric,description:description|| (kind==='income'?'Nova entrada':category),category:kind==='income'?'Renda':category,pillar,date:new Date().toISOString().slice(0,10)});close()}; return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modal-head"><div><span>NOVO LANÇAMENTO</span><h2>{kind==='income'?'Registrar entrada':'Registrar saída'}</h2></div><button onClick={close}><X/></button></div><label>Valor (R$)<input className="money-input" autoFocus inputMode="decimal" placeholder="0,00" value={value} onChange={e=>setValue(e.target.value)}/></label><label>Descrição<input placeholder={kind==='income'?'Ex.: Salário mensal':'Observação opcional'} value={description} onChange={e=>setDescription(e.target.value)}/></label>{kind==='expense'&&<><label>Origem<select value={pillar} onChange={e=>setPillar(e.target.value as Pillar)}><option value="common">Uso comum</option><option value="reserve">Reserva</option><option value="investments">Investimentos</option></select></label><div className="category-grid">{categories.map(([name,emoji])=><button className={category===name?'selected':''} onClick={()=>setCategory(name)} key={name}><span>{emoji}</span>{name}</button>)}</div></>}{kind==='income'&&numeric>0&&<div className="split"><p>Distribuição automática</p><div><span>50% <b>{money.format(new Decimal(numeric).times(.5).toNumber())}</b></span><span>30% <b>{money.format(new Decimal(numeric).times(.3).toNumber())}</b></span><span>20% <b>{money.format(new Decimal(numeric).times(.2).toNumber())}</b></span></div></div>}<button className="submit" onClick={confirm}>Confirmar lançamento</button></div></div> }
